### ISSUE TITLE
Any instructions for nadiaholmquist/arch-pbp users?

### ISSUE THREAD

**Issue by thebitstick** [nadiaholmquist/archiso-pbp#1]
Do I need to do anything to my installation of Arch?

**Comment by nadiaholmquist** [comment]
Not really, you can switch to my repo which you can find in the FAQ for somewhat more timely kernel updates, but otherwise you don't have to do anything.

**Comment by thebitstick** [comment]
Should I replace linux-pinebookpro with linux-pbp?

**Comment by nadiaholmquist** [comment]
Yes. You can also replace the uboot package if you want to, but it's not required.

**Comment by thebitstick** [comment]
I tried rebooting and I ended up in NetBSD.





jk looks like uboot was configured to boot from SD card first now, and I had a NetBSD SD installed.
I can submit a PR for these instructions to be added to the FAQ if wanted!
Thank you, closing now.

**Comment by nadiaholmquist** [comment]
Correct, uboot in my repo is configured to look for USB first, then SD, then eMMC.
