### ISSUE TITLE
extlinux config for luks encrypted disk

### ISSUE THREAD

**Issue by lynchc** [nadiaholmquist/archiso-pbp#3]
Having trouble finding information on what to set my extlinux.conf to in order for me to be able to get the password prompt on boot to decrypt the root volume. I went through and found some old [funtoo](https://www.funtoo.org/Extlinux) docs but that didn't work. Also went through the config for [syslinux](https://wiki.archlinux.org/index.php/Syslinux). Curious if you've ever tried anything like this.

**Comment by FritzJo** [comment]
I got it to work using the following config:
```
LABEL Arch Linux ARM
KERNEL /Image
FDT /dtbs/rockchip/rk3399-pinebook-pro.dtb
APPEND initrd=/initramfs-linux.img console=tty1 rootwait cryptdevice=UUID=YOUR-UUID:cryptroot root=/dev/mapper/cryptroot rw
```
And this Guide was quite useful https://rudism.com/installing-arch-linux-on-the-pinebook-pro/ (The needed changes for LUKS are at the bottom of the page)

**Comment by lynchc** [comment]
I must've made a mistake the first time through. This works. Thx
