### ISSUE TITLE
More Info on "System doesn't wake up from suspend"

### ISSUE THREAD

**Issue by thestr4ng3r** [nadiaholmquist/archiso-pbp#5]
I had encountered the "System doesn't wake up from suspend" issue mentioned in https://github.com/nadiaholmquist/archiso-pbp/blob/master/FAQ.md#system-doesnt-wake-up-from-suspend before on a custom arch installation (not from this repo) and was able to temporarily work around it the same way it is described there, but without being able to track down the root cause of it so far.

My question now is, since you seem to have a bit more insight in this, is there any further info or a ticket somewhere about this specifically where I could track the progress or get more info about the initial cause?

**Comment by nadiaholmquist** [comment]
The cause from what I understand is an issue in upstream Trusted Firmware-A, it's for some reason that is not quite known yet unable to wake the sudden after suspend. One of the developers of TF-A is working on solving the problem, but it's turning out to be quite difficult to figure out what is going wrong and what is needed to fix it.

Don't think there's a thread or anything about this anywhere, your best bet for updates on it is to follow the #pinebook chat.

**Comment by thestr4ng3r** [comment]
Thanks for the info, I will follow the irc.
