### ISSUE TITLE
pacman cannot look up PGP key remotely

### ISSUE THREAD

**Issue by kgrossjo** [nadiaholmquist/archiso-pbp#6]
I'm near the beginning of my Arch Linux journey.  I turned off the EMMC (because I hosed it and it will not boot from SD otherwise), then booted from archiso-pbp from the SD card, then turned on EMMC again, then created partitions and did some dance regarding LVM and LUKS and then I mounted partitions.

For some reason, I thought it is good to install some package (before calling pacstrap), so I ran `pacman -Syu` which tells me that the key "CB038310BB90925D8F1CAE63955129793AA3C36B" for the "pinebook" repo was unknown and could not be looked up remotely.  (I typed the key in, so there might be a typo.)

There was no keyserver configured.  So I tried to configure several keyservers in `/etc/pacman.d/gnupg/gpg.conf`, but it did not help.  (I tried each of `keyserver hkp://keyserver.kjsl.com:80`, `keyserver hkp://pool.sks-keyservers.net`, `hkp://pgp.mit.edu:11371`, and then all of them.)

I also tried to tweak the `SigLevel` setting for the pinebookpro repo in `/etc/pacman.conf`, with little result.

Oh!

After reading the man page, I see that I can do `SigLevel Never`, and that does in fact work.  But I guess it was not intended to make the user configure that.

**Comment by defini-tiv** [comment]
I got the same error from running pacstrap, but running the following commands from the [releases](https://github.com/nadiaholmquist/archiso-pbp/releases) did help:
```
pacman-key --recv-keys 955129793AA3C36B
pacman-key --lsign-key 955129793AA3C36B
```
just replace the key with the one in your error message.
