### ISSUE TITLE
Getting wifi up and running

### ISSUE THREAD

**Issue by kgrossjo** [nadiaholmquist/archiso-pbp#7]
I tried to follow the `README.md` and the Arch Linux installation guide.  I was not able to get networking in the installation image, but I found instructions here:

https://www.reddit.com/r/archlinux/comments/ifpinv/cant_connect_to_wifi/g2p819y/?context=3

I wonder if it makes sense to mention this in the `README.md`?

In the installation image, I did the following:

* `systemctl enable --now systemd-networkd systemd-resolved iwd`
* `networkctl status -a` -- see that Wifi is down
* Create file `/etc/systemd/network/20-wireless.network` with this content:
  ```
  [Match]
  Name=wlan0
  [Network]
  DHCP=yes
  ```
* `systemctl restart systemd-networkd`
* `iwctl`, then enter at the prompt: `station wlan0 connect <my_ssid>`, then `exit`
* `networkctl status -a` -- see that Wifi is up

Into the installed system (i.e., after `arch-chroot`), I installed the packages `systemd` and `iwd`, then `systemctl enable systemd-networkd systemd-resolved iwd`, then created the file `/etc/systemd/network/20-wireless.network` as above.

If I'm not mistaken, I had to run `iwctl` with `station wlan0 connect <my_ssid>` after booting the installed system.

I am not familiar with Arch Linux, specifically its stance on systemd.  So perhaps adding information how to get it running in the installed system would be too much.  But the installation image clearly runs systemd, so I feel adding the information for the installation image is very apropos for this documentation.

What do you think?

**Comment by MatusFrick** [comment]
Hi, 

Config used by you can be found in [arch wiki installation guide](https://wiki.archlinux.org/index.php/Installation_guide#Connect_to_the_internet). There is a link to iwctl and also link to [systemd config file](https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/configs/releng/airootfs/etc/systemd/network/20-wireless.network). Therefore, I don't think it is necessary to add this to `README.md`.

FYI I used to connect to wifi with `wifi-menu` command during the installation process.

**Comment by kgrossjo** [comment]
Interesting.  I had read that section in the installation guide without following the links.  And sure enough, following the systemd-networkd link provides that missing information, and more.  Now I have learned a valuable lesson about reading the Arch Linux documentation.  Thank you, @MatusFrick!
