### ISSUE TITLE
Any help on getting suspend working ?

### ISSUE THREAD

**Issue by Frans-Willem** [nadiaholmquist/archiso-pbp#9]
Thanks for setting this up, installing Arch using this ISO was almost as easy as on x86-64 :)

Nevertheless, there's one issue that's bugging me: Whenever my pbp tries to sleep (e.g. when I close the lid), it just locks up, and stops doing anything. Only way to revive is through holding the power button for 10 sec, and then hitting it again, causing a reset.

Is anyone else having more luck ? Any ideas on how to troubleshoot this ?

I've seen Manjaro users recommend uboot-bsp, but I'm not entirely sure where I'd get that.

**Comment by adds68** [comment]
Not sure if you saw this in the FAQ https://github.com/nadiaholmquist/archiso-pbp/blob/master/FAQ.md#system-doesnt-wake-up-from-suspend ?
